package com.woniu.domain;
// Generated 2019-7-26 16:38:10 by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private Integer did;
	private String dname;
	private Set emps = new HashSet(0);

	public Dept() {
	}

	public Dept(String dname, Set emps) {
		this.dname = dname;
		this.emps = emps;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public Set getEmps() {
		return this.emps;
	}

	public void setEmps(Set emps) {
		this.emps = emps;
	}

}
